name: CI

on:
  pull_request:
    branches: [ release ]

jobs:
  test-action:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Run Swellow Action (help command)
        uses: ./. # use the action defined in this repo
        with:
          command: help
          connection-string: "postgres://user:pass@localhost/db"
          migrations-directory: ./migrations
          verbose: true
